# Generated by Django 4.2.2 on 2025-08-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
