# Generated by Django 4.2.2 on 2025-09-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("successful", "Успешно"),
                            ("unsuccessful", "Не успешно"),
                        ],
                        max_length=20,
                    ),
                ),
                ("server_response", models.TextField()),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                    ),
                ),
            ],
        ),
    ]
