# Generated by Django 4.2.2 on 2025-09-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_mailingattempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
