# Generated by Django 4.2.2 on 2025-08-14 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [
                    ("can_all_view_recipients", "Просмотр всех получателей"),
                    ("can_delete_recipient", "Удаление получателя"),
                    ("can_create_recipient", "Добавление получателя"),
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
    ]
